import Head from 'next/head';
import { useRouter } from 'next/router';

import Item from '@/components/Item';
import Header from '@/components/layout/Header';
import styles from '@/styles/Home.module.css';

const items = [
  {
    image: '/item-1.png',
    alt: 'Akang Group',
    liked: true,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Janji Jiwa',
    liked: false,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Akang Group',
    liked: true,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Janji Jiwa',
    liked: false,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Akang Group',
    liked: true,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Janji Jiwa',
    liked: false,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Akang Group',
    liked: true,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
  {
    image: '/item-1.png',
    alt: 'Janji Jiwa',
    liked: false,
    rating: '4.69 (200 Reviews)',
    slot: 69,
    price: '69.420.000',
  },
];

const ParticularItem = () => {
  const router = useRouter();
  const { id } = router.query;

  if (!id) {
    return <></>;
  }

  const itemId = parseInt(Array.isArray(id) ? id[0] : id);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login - TikarKU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={`${styles.main} py-8 px-0 md:px-12`}>
        <Item {...items[itemId]} />
      </main>
    </div>
  );
};

export default ParticularItem;
