import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '@/components/layout/Header';
import styles from '@/styles/Home.module.css';

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login - TikarKU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={`${styles.main} py-8 px-0 md:px-48`}>

      </main>
    </div>
  );
};

export default Login;
